[project]
name = "daacda-static"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "acdh-cfts-pyutils>=0.2",
    "acdh-tei-pyutils>=1.6",
    "csae-pyutils>=0.2",
    "jinja2>=3.1.6",
]
